name: CI - customer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "customer/**"
  pull_request:
    paths:
      - "customer/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bun
        run: |
          curl -fsSL https://bun.com/install | bash
          echo "$HOME/.bun/bin" >> "$GITHUB_PATH"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run customer unit tests + coverage
        run: make customer coverage_ci

      - name: Run customer and blockchain integration tests + coverage
        run: make COVERAGE_CI=true run/integration/tests/between/customer/and/local blockchain

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./customer/coverage/lcov-<unit>.info,./customer/coverage/lcov-<integration>.info
